config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics do 
  	resources :comments,  only: [:new, :create, :edit, :update, :destroy]
    resources :subscribes, :controller => :subscribes, only: [:create, :destroy]  
    # /topics/:topic_id/subscribes
    
      member do 
        post :like
        post :unlike

      end  
  end
  get '/profile/:nickname' => 'profiles#show'  , as: :profile
  resources :users do 	
  	resource :profile , :controller => :profiles, :except => [:show]  do  
      collection do 
        get :likes
        get :subscribes

      end
    end
  end
  
  namespace :api do
   constraints(host: 'howard.localhost') do  
    resources :topics , :only => [:index, :show]
    root to:  "topics#index"
   end 
  end 




  resource :profile , :controller => :profiles 
  
  get 'tags/:tag', to: 'topics#index', as: "tag"
  get '/about' => 'topics#about', :as => "about"
  root :to => 'topics#index'
end
  

app/models/profile.rb
class Profile < ApplicationRecord
	
	belongs_to :user

	def short_name
		self.email.split("@").first        	
  	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
		before_action :find_user 
		before_action :authenticate_user!, :except => [:show]
		
		def show
			# @profile = User.find_by_nickname(params[:nickname]).profile
			@profile = Profile.find_by_nickname!(params[:nickname])
			@profiletopics = @user.topics.page(params[:page_topic]).per(10)
			@profilecomment = @user.comments.includes(:topic).page(params[:page_comment]).per(10)
		end

		def new
			@profile = @user.build_profile
		end	

		def create
			@profile = @user.build_profile(profile_params)
			if @profile.save
				redirect_to user_profile_path(@user)
			else
				render :action => :edit
			end	
		end

		def edit
			@profile = current_user.profile
		end

		def update
			@profile = current_user.profile

			if @profile.update(profile_params)
				redirect_to user_profile_path(@user)
			else
				flash[:alert] = "Edit Failed"
				render :action => :edit
			end	
		end

		def likes
			@profile = @user.profile
			@profilelike = @user.like_topics.page(params[:page_like]).per(10)
		end

		def subscribes
			@user = User.includes(:subscribes).find(params[:user_id])
			@profile = @user.profile

			
		end



		private

		def find_user
			@user = User.find(params[:user_id])
		end

		def profile_params
			params.require(:profile).permit(:nickname, :bio)
			
		end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h1><%= current_user.short_name%>的個人檔案</h1>

<div><img src="https://api.fnkr.net/testimg/350x200/00CED1/FFF/?text=img+placeholder"></div>


<%= form_for @profile , :url => user_profile_path(@user) , :method => :patch do |f| %>

<%=f.label :nickname , "nickname"%>
<%=f.text_field :nickname, :class => "form-control"  %>
<br \>
<%=f.label :bio, "Biography"%>
<%=f.text_area :bio, :class => "form-control"  %>
<br>
<%= f.submit "儲存設定" , :class => "btn btn-success"%>

<% end %>

app/views/profiles/likes.html.erb
<h1><%= @user.short_name%>的個人檔案</h1>

<div><img src="https://api.fnkr.net/testimg/350x200/00CED1/FFF/?text=img+placeholder"></div>


<table class="table table-striped">
	

		<th><span style="font-size: 35px">Nickname :     <%= @profile.try(:nickname) %></span></th>
		<tbody>
	<tr></tr>
		<td><span style="font-size: 25px">Biography</span></td>
	<tr></tr>
		<td><%= @profile.try(:bio) %></td>
	<tr>
		<%= link_to "編輯個人資料" , edit_user_profile_path(@user) , :class => "btn btn-info" %>
		<%= link_to "個人資料" , user_profile_path(@user) , :class => "btn btn-info" %>
	</tr>
		<td><span style="font-size: 20px "><%= @profile.try(:nickname) %> 喜歡的文章</span></td>
		<td>瀏覽人數</td>
	<tr><% @user.like_topics.each do |liketopic| %></tr>
		<td><%=  liketopic.title %></td>
		<td><%=  liketopic.views %></td>
		<td></td>
		<td></td>
		<% end %>	
		
	</tbody>
		
</table>

app/views/profiles/new.html.erb
<h1><%= current_user.short_name%>的個人檔案</h1>

<div><img src="https://api.fnkr.net/testimg/350x200/00CED1/FFF/?text=img+placeholder"></div>


<%= form_for @profile , :url => user_profile_path(@user) , :method => "post" do |f| %>

<%=f.label :nickname , "nickname"%>
<%=f.text_field :nickname, :class => "form-control"  %>
<br \>
<%=f.label :bio, "Biography"%>
<%=f.text_area :bio, :class => "form-control"  %>
<br>
<%= f.submit "儲存設定" , :class => "btn btn-success"%>

<% end %>

<%= link_to "Back to Profile" , edit_user_profile_path(@user) , :class => "btn btn-info"%>

app/views/profiles/show.html.erb
<h1><%= @user.short_name%>的個人檔案</h1>

<div><img src="https://api.fnkr.net/testimg/350x200/00CED1/FFF/?text=img+placeholder"></div>


<table class="table table-striped">
		<th><span style="font-size: 35px">Nickname :     <%= @profile.try(:nickname) %></span></th>
		<td></td>
		<td></td>
		<tbody>
	<tr></tr>
		<td><span style="font-size: 25px">Biography</span></td>
		<td></td>
		<td></td>
	<tr></tr>
		<td><%= @profile.try(:bio) %></td>
		<td></td>
		<td></td>
	<tr>
		<% if current_user == @user%>
			<%= link_to "編輯個人資料" , edit_user_profile_path(@user) , :class => "btn btn-info" %>
		<% end %>	
		<%= link_to "#{@user.short_name} 喜歡的文章" , likes_user_profile_path(:user_id => @user.id) , :class => "btn btn-primary" %>	
		<%= link_to "#{@user.short_name} 的收藏" , subscribes_user_profile_path(@user) , :class => "btn btn-success" %>
	</tr>
		<td><span style="font-size: 25px "><%= @profile.try(:nickname) %> 的文章</span></td>
		<td>回覆數量</td>
	<tr><% @profiletopics.each do |t|%></tr>
		<td><%= t.title %></td>
		<td><%= t.comments.count %></td>
		<td></td>
			<td></td>	
		<% end %>
	</tbody>
		
</table>

<div><%= paginate @profiletopics , :theme => 'twitter-bootstrap-3', :param_name => "page_topic" %></div> 
<%= link_to "Back to Topics" ,topics_path , :class => "btn btn-info"%>

<br \> 	
<table class="table table-striped">
	<th><span style="font-size: 25px"><%= @profile.try(:nickname) %> 回覆的文章</th>
	<td>回覆文章</td>
	<tr><% @profilecomment.each do |c| %></tr>
		<% if c.topic != nil %>
			<td><%= c.content %></td>
			<td><%= c.topic.title %></td>
		<% else %>
				
		<% end %>
	<% end %>


</table>

<div><%= paginate @profilecomment , :theme => 'twitter-bootstrap-3', :param_name => "page_comment" %></div> 
<%= link_to "Back to Topics" ,topics_path , :class => "btn btn-info"%>

app/views/profiles/subscribes.html.erb
<h1><%= @user.short_name%>的個人檔案</h1>

<div><img src="https://api.fnkr.net/testimg/350x200/00CED1/FFF/?text=img+placeholder"></div>


<table class="table table-striped">
	

		<th><span style="font-size: 35px"><%= @profile.try(:nickname) %> 的收藏</span></th>
		<td><span style="font-size: 20px">瀏覽人數</span></td>
		<tbody>
	<tr>
		<%= link_to "編輯個人資料" , edit_user_profile_path(@user) , :class => "btn btn-info" %>
		<%= link_to "個人資料" , user_profile_path(@user) , :class => "btn btn-primary" %>
		<%= link_to "#{@user.short_name} 喜歡的文章" , likes_user_profile_path(:user_id => @user.id) , :class => "btn btn-primary" %>	
	</tr>
		
	<tr><% @user.subscribe_topics.each do |s| %></tr>
		<td><%=  s.title %></td>
		<td><%=  s.views %></td>
		<% end %>	
		
	</tbody>
		
</table>
<div><%#= paginate @profilelike , :theme => 'twitter-bootstrap-3', :param_name => "page_like" %></div> 
<%= link_to "Back to Topics" ,topics_path , :class => "btn btn-info"%>