config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics do 
  	resources :comments,  only: [:new, :create, :edit, :update, :destroy]
    resources :subscribes, :controller => :subscribes, only: [:create, :destroy]  
    # /topics/:topic_id/subscribes
    
      member do 
        post :like
        post :unlike

      end  
  end
  get '/profile/:nickname' => 'profiles#show'  , as: :profile
  resources :users do 	
  	resource :profile , :controller => :profiles, :except => [:show]  do  
      collection do 
        get :likes
        get :subscribes

      end
    end
  end
  
  namespace :api do
   constraints(host: 'howard.localhost') do  
    resources :topics , :only => [:index, :show]
    root to:  "topics#index"
   end 
  end 




  resource :profile , :controller => :profiles 
  
  get 'tags/:tag', to: 'topics#index', as: "tag"
  get '/about' => 'topics#about', :as => "about"
  root :to => 'topics#index'
end
  

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title
	belongs_to :user
	has_many :comments, :dependent => :destroy
	has_many :topic_categoryships, :dependent => :destroy
	has_many :categories , :through => :topic_categoryships
	has_many :likes , :dependent => :destroy
	has_many :like_users , :through => :likes , :source => :user
	has_many :subscribes , :dependent => :destroy
  	has_many :subscribe_users , :through => :subscribes , :source => :user
  	has_many :topic_tagships, :dependent => :destroy
	has_many :tags , :through => :topic_tagships
	has_many :photos, :dependent => :destroy

	delegate :email, :to => :user , :prefix => true, :allow_nil => true
	delegate :content, :to => :comment , :prefix => true, :allow_nil => true

	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/blank.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  	def all_tags=(names)
	  self.tags = names.split(",").map do |name|
	      Tag.where(name: name.strip).first_or_create!
	  end
	end

	def all_tags
	  self.tags.map(&:name).join(", ")
	end

	def self.tagged_with(name)
  	Tag.find_by_name!(name).topics
	end
	
	def api_info
		return {
			:id => self.id,
			title: self.title,
			content: self.content
		}
	end


end

app/controllers/api/topics_controller.rb
class Api::TopicsController < Api::BaseController


	def index
		@users = User.all
		@topics = Topic.all

		render :json => { :users => @users.map{|u| u.api_info}, :topics => @topics.map{|t| t.api_info} }
	end

end	

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	
	before_action :authenticate_user!, except: [:index,:show]
	before_action :set_topic , :only => [:edit , :update, :destroy, :like, :unlike]

	
	def index
		



		if params[:keyword]
			@topics = Topic.where( [ "title like ?", "%#{params[:keyword]}%" ] )
		elsif params[:tag]
  		@topics = Topic.tagged_with(params[:tag])	
		else
			@topics = Topic.all
		end

		if params[:order]
			sort_by = (params[:order] == 'title') ? 'title' : 'id'
			@topics = @topics.order(sort_by)

		elsif params[:comment_time]#照回覆時間進行排序
			@topics = @topics.includes(:comments).order("comments.created_at DESC")

		elsif params[:comment_numbers]#照回覆數進行排序
			@topics = @topics.order("comments_count DESC")
		
		elsif params[:views_number] 
			@topcis = @topics.order("views DESC")
		end	
		
		if params[:default]
			@topics = @topics.order("created_at DESC")
		elsif params[:infernal]
			@category = Category.find(params[:infernal])
			@topics = @category.topics
		elsif params[:ocean]
			@category = Category.find(params[:ocean])
			@topics = @category.topics
		elsif params[:earth]
			@category = Category.find(params[:earth])
			@topics = @category.topics
		elsif params[:cloud]
			@category = Category.find(params[:cloud])
			@topics = @category.topics
		elsif params[:elder]
			@category = Category.find(params[:elder])
			@topics = @category.topics					
		end	
		# byebug

		@topics = @topics.includes(:user, :comments, :subscribes).page(params[:page]).per(5)
		

		if params[:id]
			@topic = Topic.find(params[:id])
		else
			@topic = Topic.new
		end	
		
	end

	def show		
		@topic = Topic.includes(:comments).find(params[:id])		
		@topic.views += 1
		@topic.save
		@users = @topic.like_users
		@like = current_user.likes.find_by(:topic_id => params[:id])
		@photos = @topic.photos

		
		if params[:id] && params[:comment_id]
			@comment = @topic.comments.includes(:user).find(params[:comment_id])
		else
			@comment = Comment.new
		end	
	end

	def new
		@topic = current_user.topics.new
	end

	def create
		@topic = current_user.topics.new(topic_params)
		@topics = Topic.page(params[:page]).per(5)
		if @topic.save
			# UserMailer.notify_new_topic(current_user, @topic).deliver_now!
		   redirect_to topics_path
		else 
		   render :action => :index
		end   
	end

	def edit
		@photos = @topic.photos
	end

	def update
		@topics = Topic.all.order("id DESC").page(params[:page]).per(5)
		@topic = Topic.find(params[:id])

		if params[:remove_upload_file] == "1"
			@topic.logo = nil
		elsif params[:remove_upload_photo] == "2"
			@topic.photos.delete_all	
		end	

		if @topic.update(topic_params)&&(current_user == @topic.user)
				if params[:images]
						params[:images].each {|image| @topic.photos.create(image: image) }	
						redirect_to topic_path(@topic)
				else
					flash[:alert] = "Failed to Update"
					render :action => :index
				end
		end		
	end

	def destroy
		if current_user == @topic.user
			@topic.destroy
		end	
		respond_to do |format|
			format.html{
				redirect_to topics_path		
			 }
			format.js
		end	
	end

	def about
		@topics = Topic.all
		@user = current_user
		@comments = Comment.all
	end

	def like
		@like = current_user.likes.build(:topic_id => params[:id])
		@like.save
		respond_to do |format|
			format.js
		end	
	end

	def unlike
		@like = current_user.likes.find_by_topic_id(params[:id])
	    @like.destroy
		@like = nil
		respond_to do |format|
			format.js
		end	
		
	end



	private

	def set_topic
		@topic = Topic.find(params[:id])
	end

	def topic_params
		params.require(:topic).permit(:title, :content, :status, :logo, :photos, :all_tags ,:user_id, :comment_id, :category_ids =>[])
	end

end

app/helpers/topics_helper.rb
module TopicsHelper

	def tagname(tag)
      tag.split(" ")
    end
    
    def tag_links(tags)
	  tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
	end
end

app/views/topics/_comment.html.erb
<tr>
	<td><span style="font-size: 20px">Comment :</span></td>
	<td></td>
	<td ></td>
	<td></td>

	<td><span style="text-align: left">Poster</span></td>

</tr>
<% @topic.comments.each do |c| %>
<tr id="comment-<%= c.id %>">

	<% if c.status == 'published' %>
		<td><%= c.content %></td>
		<td><%= image_tag c.avatar.url(:thumb)%></td>
		<td></td>
		<td>
			<% if current_user == c.user %>	
				<%= link_to "Edit" , topic_path(:id => @topic.id , :comment_id => c.id), :class => "btn btn-primary" %>
			    <%= link_to "Delete" , topic_comment_path(@topic,c.id), :method => "delete", :remote => true , :class => "btn btn-danger" %>
		    <% end %>	
	    </td>
		<td><%= link_to c.user.short_name , user_profile_path(c.user.id)  %></td>

	<% elsif c.status == 'draft' && current_user == c.user %>
		<td><p style="color: #f0f"><%= c.content %></p></td>
		<td><%= link_to "Edit" , topic_path(:id => @topic.id , :comment_id => c.id), :class => "btn btn-primary" %>
			<%= link_to "Delete" , topic_comment_path(@topic,c.id), :method => "delete", :remote => true, :class => "btn btn-danger" %></td>
		<td><%= c.user.short_name %></td>

	<% end %>

		
</tr>
<% end %>

app/views/topics/_form.html.erb
<% if @topic.errors.any?%>
	<% @topic.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>
<% end %>


<div class="form-group">
	<%= f.label :title , "Topic Title"%>
	<%= f.text_field :title , :class => "form-control"%>
</div>

<div class="form-group">
	<%= f.label :logo , "上傳照片" %>
	<%= f.file_field :logo %>
	<% if @topic.logo.exists?%>	
		<%= check_box_tag "remove_upload_file", "1" %>移除上傳檔案
	<% end %>
</div>

<div class="form-group">
	<%= f.label :photos , "上傳多張照片", :class => "control-label" %>
	<%= file_field_tag "images[]", type: :file, multiple: true %>
	<% if @topic.photos.exists?%>	
		<%= check_box_tag "remove_upload_photo", "2" %>移除圖片
	<% end %>
</div>

<div class="form-group">
	<%= f.label :status, "Status" %>
    <%= f.select :status, [["Published", "published"],["Draft","draft"]] , :class => "form-control" %>
</div>


<div class="form-group">
		<%= f.collection_check_boxes(:category_ids ,Category.all ,:id ,:name )%>
</div>

<div class="form-group">
	<%= f.label :all_tags, "Tag" %>
  <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
</div>

<div class="form-group">
	<%= f.label :content , "Topic Content"%>
	<%= f.text_area :content , :class => "form-control"%>
</div>

app/views/topics/_like.html.erb
<% if @like %>  
		<%= link_to "unlike", unlike_topic_path(:id => topic.id) , :remote => true, :class => "btn btn-danger", :method => :post, :style => "font-size: 8px" %>
<% else %>
		<%= link_to "like", like_topic_path(:id => topic.id) , :remote => true, :class => "btn btn-primary", :method => :post, :style => "font-size: 8px" %>
<% end %>
<!--// 可以直接使用Button_to(超級小的form，只有一個按鈕的form)，其預設的方法就是post-->

app/views/topics/_subscribe.html.erb
<% if current_user %>	
	<% if current_user.subscribes.find_by_topic_id(topic.id) %>  
			<%= link_to "", topic_subscribe_path(:topic_id => topic.id, :id => current_user.subscribes.find_by_topic_id(topic)) ,:class => "btn btn-danger btn-xs glyphicon glyphicon-star-empty aria-hidden = true",:remote => true, :method => :delete, :style => "font-size: 5px" %>		
	<% else %>
			<%= link_to "", topic_subscribes_path(:topic_id => topic.id)  ,:class => "btn btn-primary btn-xs glyphicon glyphicon-star aria-hidden = true", :remote => true, :style => "font-size: 5px", :method => :post %>
	<% end %>
<% end %>

app/views/topics/about.html.erb
<h1>About us</h1>

<span style="font-size: 20px">"Asymmetrical organic tofu semiotics keytar 3 wolf moon. Thundercats spanhoto booth banjo occupy five dollar toast. Tumblr flexitarian diy migas ugh godard organic vice."</span>

 
<div style="font-size: 30px">We have <%= @topics.all.count %>   users</div>
<br \>
<div style="font-size: 30px">and <%= @comments.all.count%>   comments</div>
 
<% if current_user %>
<div> and  <%= @user.short_name %> have <%=@user.comments.count   %>  comments</div>
<% end %>


<%= link_to "Back to Index" , topics_path , :class => "btn btn-primary"%>

app/views/topics/destroy.js.erb
$("#topic-<%= @topic.id %>").remove();

app/views/topics/edit.html.erb
<h1><%= @topic.title%></h1>

<%= form_for @topic , :url => topic_path(@topic) , :method => :patch do |f| %>

<%= render :partial => "form" , :locals => { :f => f }%>	
<%= f. submit :submit_name%>
<% end %>

app/views/topics/index.html.erb
<h1>Topics List</h1> <span><%= link_to "About" , about_path , :method => :get , :class => "btn btn-info"%></span>
<% if @topic.errors.any? %>
	<% @topic.errors.full_messages do |msg| %>
	<span style="font-size: 15px"><%= msg%></span>
	<% end %>
<% end %>

<%= form_for @topic, html: { multipart: true }  do |f|%>
<%= render :partial => "form" , :locals => { :f => f}%>

<%= f.submit "Confirm", :class => "btn btn-success"%>
<%#= f.submit "Cancel" , :class => "btn btn-warning"%>
<% end %>
<br \>
<%= form_tag topics_path, :method => :get do %>
  <%= text_field_tag "keyword", nil, :placeholder => "Search for Title" %>
  <%= submit_tag "Search" %>
<% end %>
<br \>

<%= link_to "Default" , topics_path(:default => "ddd"), :class => "btn btn-info " , :style =>"border-radius: 50%"%>
<%= link_to "Infernal" , topics_path(:infernal => "1"), :class => "btn btn-primary " , :style =>"border-radius: 50%"%>
<%= link_to "Ocean" , topics_path(:ocean => "2"), :class => "btn btn-primary " , :style =>"border-radius: 50%"%>
<%= link_to "Earth" , topics_path(:earth => "3"), :class => "btn btn-primary " , :style =>"border-radius: 50%"%>
<%= link_to "Cloud" , topics_path(:cloud => "4"), :class => "btn btn-primary " , :style =>"border-radius: 50%"%>
<%= link_to "Elder" , topics_path(:elder => "5"), :class => "btn btn-primary " , :style =>"border-radius: 50%"%>

<%# @topics.each do |topic| %>
	<%#=raw tag_links(topic.all_tags)%>
<%# end %>

<br \>
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-striped table-hover">
				<td><%= link_to "Topic" , topics_path(:order => "title")%></td>
				<td>Poster</td>
				<td><%= link_to "回覆數" , topics_path(:comment_numbers => "comments_number")%></td>
				<td><%= link_to "最新回覆時間" ,topics_path(:comment_time => "comments_at")%></td>
				<td><%= link_to "瀏覽人數" , topics_path(:views_number => "viewers" )%></td>
				<td></td>
				<td>誰回覆您</td>


				<% @topics.each do |topic| %>
					<% if topic.status == "published" %> 	
						<tr id="topic-<%= topic.id%>">

						<td>
							<span id="index-subscribe-<%= topic.id %>">
								<%= render :partial => "subscribe", :locals => { :topic => topic} %>
							</span>	
							<span style="font-size: 20px"><%= link_to topic.title, topic_path(topic) %></span>
						</td>	
						<td><%= link_to topic.user.try(:short_name) ,profile_path(nickname: topic.user.profile.nickname, user_id: topic.user.id) %></td>				
						<td><%= topic.comments_count %></td>
						<td>
						<!-- 時間排序後，第一筆及最後一筆資料會互換，所以在發佈時間排序時，須作調整 -->
							<% if topic.comments.last && params[:comment_time] %>
								<%= topic.comments.first.created_at %>
							<%else%>
								<%= topic.comments.last.try(:created_at)%>
						</td>
						<td><%= topic.views %></td>
						<td>
							<% if current_user == topic.user %>
							<%= link_to "edit" , topics_path(:id => topic.id) , :class => "btn btn-primary"%>
							<%= link_to "Delete" , topic_path(topic) , :method => :delete ,:remote => true , :class => "btn btn-danger"%>
							<% end %>
							<span id="index-like-<%= topic.id %>"><%= render :partial => "like", :locals => { :topic => topic } %></span>
							<span id="index-like-number-<%= topic.id %>"><%= topic.likes.count %> likes</span>
						</td>
						<% end %>
						<td>
						<% if topic.comments.present? %>
							<%= link_to topic.comments.last.user.short_name, user_profile_path(topic.comments.last.user.id) %>
						<% end %>	
							
						</td>
						
						</tr>
					<% elsif topic.status == "draft" && current_user == topic.user %>	
						<tr id="topic-<%= topic.id%>">

						<td><span style="font-family: impact"><%= link_to topic.title, topic_path(topic) %></span></td>	
						<td><%= topic.user.try(:short_name) %></td>				
						<td><%= topic.comments_count %></td>
						<td>
							<% if topic.comments.last && params[:comment_time] %>
								<%= topic.comments.first.created_at %>
							<%else%>
								<%= topic.comments.last.try(:created_at)%>
						</td>
						<td><%= topic.views %></td>
						<td>
							<%#= link_to "show" , topic_path(topic) , :class => "btn btn-success"%>
							<%= link_to "edit" , topics_path(:id => topic.id) , :class => "btn btn-primary"%>
							<%= link_to "Delete" , topic_path(topic) , :method => :delete ,:remote => true , :class => "btn btn-danger"%>
						</td>
						<% end %>
						<td>
						<% if topic.comments.present? %>
							<%= topic.comments.last.user.short_name %>
						<% end %>	
							
						</td>
						
						</tr>
					<% end %>
				<% end %>
			</table>
		</div>
					<%= link_to "Post Topic" , new_topic_path , :class => "btn btn-info" %>
					<div><%= paginate @topics, :theme => 'twitter-bootstrap-3'%></div>
	</div>
</div>

app/views/topics/like.js.erb
$('#like-number').html('<%= @topic.likes.count %>  likes')
$('#like').html('<%= j render(:partial => "like", :locals => { :topic => @topic}) %>')
$('#index-like-number-<%= @topic.id %>').html('<%= @topic.likes.count %>  likes')
$('#index-like-<%= @topic.id %>').html('<%= j render(:partial => "like", :locals => { :topic => @topic}) %>')

app/views/topics/new.html.erb
<h1>Post Topic</h1>

<%= form_for @topic , :url => topics_path do |f|%>


<%= render :partial => "form" , :locals => { :f => f} %>



<%= f.submit :submit_name %>

<% end %>	

app/views/topics/show.html.erb
<h1><span style="font-size: 50px"><%= @topic.title%></span></h1>
<span style="font-size: 15px"><%=raw tag_links(@topic.all_tags)%></span>

<div id="like-number">
	<%= @topic.likes.count %>  likes
</div>
<div id="like">
	<%= (render :partial => 'like', :locals => { :topic => @topic }) %>	
</div>

<div id="subscribe">
	<%= (render :partial => 'subscribe', :locals => { :topic => @topic}) %>
</div>

<div>
	<%= image_tag @topic.logo.url(:medium) %>
	<% if @photos.exists? %>
		<% @photos.each do |pic| %>
			<%= image_tag (pic.image.url(:medium)) %>	
		<% end %>	
	<% else %>
		無其他圖片	
	<% end %>	
</div>
<span style="font-size: 35px">content</span>

<br \>
<table class="table table-striped table-hover">
	<thead><span style="font-size: 20px"><%= @topic.content %></span></thead>
	<tbody id="comment-list">
		
	<%= render :partial => 'comment'  %>
				
</tbody>		
</table>
<%#if @topic.comments.errors.any?%>
	<%# @topic.comments.errors.full_messages.each do |msg|%>
	<%#= msg%>
	<%# end %>
<%# end %>



<%= form_for [@topic, @comment], :remote => true , html: { multipart: true } do |f|%> <!-- rails 會自動幫我們判別是經由create還是update -->
	<%= f.label :content ,"Comment"%>
	<%= f.text_area :content ,:class => "form-control"%>
	<div class="form-group">
		<%= f.label :avatar , "上傳圖片" %>
		<%= f.file_field :avatar %>
		<% if @comment.avatar.exists?%>	
			<%= check_box_tag "remove_comment_file", "1" %>移除上傳檔案
		<% end %>	
	</div>
	<div class="form-group">
	<%= f.label :status, "Status" %>
    <%= f.radio_button :status, "published"%>Published
    <%= f.radio_button :status, "draft"%>Draft
	</div>	

	<%= f.submit "留言" ,  :class => "btn btn-success"%>
<% end %>


<br \>
<%= link_to "Back to Index" , topics_path , :class => "btn btn-primary"%>

app/views/topics/unlike.js.erb
$('#like-number').html('<%= @topic.likes.count %>  likes')
$('#like').html('<%= j render(:partial => "like", :locals => { :topic => @topic}) %>')
$('#index-like-number-<%= @topic.id %>').html('<%= @topic.likes.count %>  likes')
$('#index-like-<%= @topic.id %>').html('<%= j render(:partial => "like", :locals => { :topic => @topic}) %>')