config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics do 
  	resources :comments,  only: [:new, :create, :edit, :update, :destroy]
    resources :subscribes, :controller => :subscribes, only: [:create, :destroy]  
    # /topics/:topic_id/subscribes
    
      member do 
        post :like
        post :unlike

      end  
  end
  get '/profile/:nickname' => 'profiles#show'  , as: :profile
  resources :users do 	
  	resource :profile , :controller => :profiles, :except => [:show]  do  
      collection do 
        get :likes
        get :subscribes

      end
    end
  end
  
  namespace :api do
   constraints(host: 'howard.localhost') do  
    resources :topics , :only => [:index, :show]
    root to:  "topics#index"
   end 
  end 




  resource :profile , :controller => :profiles 
  
  get 'tags/:tag', to: 'topics#index', as: "tag"
  get '/about' => 'topics#about', :as => "about"
  root :to => 'topics#index'
end
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    
  </head>

  <body>



	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				
				<% if flash[:notice].present? %>
					<div class="alert alert-danger" role ="alert">
						<span style="color: green"><%= flash[:notice] %></span>
					</div>
				<% end %>

				<% if flash[:alert].present? %>
					<div class="alert alert-danger" role ="alert">
						<span style="color: red"><%= flash[:alert]%></span>
					</div>
				<% end %>	
				
				
				<% if current_user %>
					<% if current_user.profile %>
						Hi ,<%= link_to current_user.email , profile_path(nickname: current_user.profile.nickname, user_id: current_user.id) %>
					<% else %>
						Hi ,<%= link_to current_user.email , new_user_profile_path(current_user) %>
					<% end  %>
				    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
				    <%= link_to('修改密碼', edit_registration_path(:user)) %> 
				  <% else %>
				    <%= link_to('註冊', new_registration_path(:user)) %> |
				    <%= link_to('登入', new_session_path(:user)) %>
				     <%= link_to "Facebook Log In", user_facebook_omniauth_authorize_path, :class => "btn btn-primary", :style => "font-size: 5px" %>
			    <% end %>
			    <% if current_user %>
				<%= image_tag current_user.gravatar_url%>
				<% end %>
				<%= yield %>
			</div>
		</div>
	</div>
	


    
  </body>
</html>